version: '3'
services:
    php:
        build: php
        volumes:
            - ./html:/var/www/html
        ports:
            - 8901:80
    sqlmap:
        build: sqlmap
        tty: true
